packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@firebase/util"
  - protobufjs
  - unrs-resolver

catalog:
  typescript: 5.9.3
  eslint: ^9.39.1
  react: 19.2.3
  react-dom: 19.2.3
  "@types/react": ~19.2.2
  "@types/react-dom": ~19.2.1
  zod: ^4.6.5
